
var pType=Runner.pages.constants.PAGE_LIST;Runner.pages.PageSettings.addPageEvent("student_course",pType,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='Import_Darjah_5';if(!pageObj.buttonEventBefore['Import_Darjah_5']){pageObj.buttonEventBefore['Import_Darjah_5']=function(params,ctrl,pageObj,proxy,pageid,rowData){params["txt"]="Berjaya Import";ctrl.setMessage("Sending request to server...");}}
if(!pageObj.buttonEventAfter['Import_Darjah_5']){pageObj.buttonEventAfter['Import_Darjah_5']=function(result,ctrl,pageObj,proxy,pageid,rowData){var message=result["txt"]+" !!!";ctrl.setMessage(message);}}
$('a[id=Import_Darjah_5]').each(function(){if(!$(this).closest('tr.gridRowAdd').length){var newId="Import_Darjah_5"+"_"+Runner.genId();this.id=newId;var button_Import_Darjah_5=new Runner.form.Button({id:newId,btnName:"Import_Darjah_5"});button_Import_Darjah_5.init({args:[pageObj,proxy,pageid]});}});});var pType=Runner.pages.constants.PAGE_LIST;Runner.pages.PageSettings.addPageEvent("student_course",pType,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='Darjah_1';if(!pageObj.buttonEventBefore['Darjah_1']){pageObj.buttonEventBefore['Darjah_1']=function(params,ctrl,pageObj,proxy,pageid,rowData){params["txt"]="Berjaya Import";ctrl.setMessage("Sending request to server...");}}
if(!pageObj.buttonEventAfter['Darjah_1']){pageObj.buttonEventAfter['Darjah_1']=function(result,ctrl,pageObj,proxy,pageid,rowData){var message=result["txt"]+" !!!";ctrl.setMessage(message);}}
$('a[id=Darjah_1]').each(function(){if(!$(this).closest('tr.gridRowAdd').length){var newId="Darjah_1"+"_"+Runner.genId();this.id=newId;var button_Darjah_1=new Runner.form.Button({id:newId,btnName:"Darjah_1"});button_Darjah_1.init({args:[pageObj,proxy,pageid]});}});});var pType=Runner.pages.constants.PAGE_LIST;Runner.pages.PageSettings.addPageEvent("student_course",pType,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='Darjah_2';if(!pageObj.buttonEventBefore['Darjah_2']){pageObj.buttonEventBefore['Darjah_2']=function(params,ctrl,pageObj,proxy,pageid,rowData){params["txt"]="Berjaya Import";ctrl.setMessage("Sending request to server...");}}
if(!pageObj.buttonEventAfter['Darjah_2']){pageObj.buttonEventAfter['Darjah_2']=function(result,ctrl,pageObj,proxy,pageid,rowData){var message=result["txt"]+" !!!";ctrl.setMessage(message);}}
$('a[id=Darjah_2]').each(function(){if(!$(this).closest('tr.gridRowAdd').length){var newId="Darjah_2"+"_"+Runner.genId();this.id=newId;var button_Darjah_2=new Runner.form.Button({id:newId,btnName:"Darjah_2"});button_Darjah_2.init({args:[pageObj,proxy,pageid]});}});});var pType=Runner.pages.constants.PAGE_LIST;Runner.pages.PageSettings.addPageEvent("student_course",pType,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='Darjah_3';if(!pageObj.buttonEventBefore['Darjah_3']){pageObj.buttonEventBefore['Darjah_3']=function(params,ctrl,pageObj,proxy,pageid,rowData){params["txt"]="Berjaya Import";ctrl.setMessage("Sending request to server...");}}
if(!pageObj.buttonEventAfter['Darjah_3']){pageObj.buttonEventAfter['Darjah_3']=function(result,ctrl,pageObj,proxy,pageid,rowData){var message=result["txt"]+" !!!";ctrl.setMessage(message);}}
$('a[id=Darjah_3]').each(function(){if(!$(this).closest('tr.gridRowAdd').length){var newId="Darjah_3"+"_"+Runner.genId();this.id=newId;var button_Darjah_3=new Runner.form.Button({id:newId,btnName:"Darjah_3"});button_Darjah_3.init({args:[pageObj,proxy,pageid]});}});});var pType=Runner.pages.constants.PAGE_LIST;Runner.pages.PageSettings.addPageEvent("student_course",pType,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='Darjah_6';if(!pageObj.buttonEventBefore['Darjah_6']){pageObj.buttonEventBefore['Darjah_6']=function(params,ctrl,pageObj,proxy,pageid,rowData){params["txt"]="Berjaya Import";ctrl.setMessage("Sending request to server...");}}
if(!pageObj.buttonEventAfter['Darjah_6']){pageObj.buttonEventAfter['Darjah_6']=function(result,ctrl,pageObj,proxy,pageid,rowData){var message=result["txt"]+" !!!";ctrl.setMessage(message);}}
$('a[id=Darjah_6]').each(function(){if(!$(this).closest('tr.gridRowAdd').length){var newId="Darjah_6"+"_"+Runner.genId();this.id=newId;var button_Darjah_6=new Runner.form.Button({id:newId,btnName:"Darjah_6"});button_Darjah_6.init({args:[pageObj,proxy,pageid]});}});});var pType=Runner.pages.constants.PAGE_LIST;Runner.pages.PageSettings.addPageEvent("student_course",pType,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='Darjah_4';if(!pageObj.buttonEventBefore['Darjah_4']){pageObj.buttonEventBefore['Darjah_4']=function(params,ctrl,pageObj,proxy,pageid,rowData){params["txt"]="Berjaya Import";ctrl.setMessage("Sending request to server...");}}
if(!pageObj.buttonEventAfter['Darjah_4']){pageObj.buttonEventAfter['Darjah_4']=function(result,ctrl,pageObj,proxy,pageid,rowData){var message=result["txt"]+" !!!";ctrl.setMessage(message);}}
$('a[id=Darjah_4]').each(function(){if(!$(this).closest('tr.gridRowAdd').length){var newId="Darjah_4"+"_"+Runner.genId();this.id=newId;var button_Darjah_4=new Runner.form.Button({id:newId,btnName:"Darjah_4"});button_Darjah_4.init({args:[pageObj,proxy,pageid]});}});});var pType=Runner.pages.constants.PAGE_LIST;Runner.pages.PageSettings.addPageEvent("student_course",pType,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='UP1';if(!pageObj.buttonEventBefore['UP1']){pageObj.buttonEventBefore['UP1']=function(params,ctrl,pageObj,proxy,pageid,rowData){params["txt"]="Exam";ctrl.setMessage("Sending request to server...");}}
if(!pageObj.buttonEventAfter['UP1']){pageObj.buttonEventAfter['UP1']=function(result,ctrl,pageObj,proxy,pageid,rowData){var message=result["txt"]+" !!!";ctrl.setMessage(message);}}
$('a[id=UP1]').each(function(){if(!$(this).closest('tr.gridRowAdd').length){var newId="UP1"+"_"+Runner.genId();this.id=newId;var button_UP1=new Runner.form.Button({id:newId,btnName:"UP1"});button_UP1.init({args:[pageObj,proxy,pageid]});}});});var pType=Runner.pages.constants.PAGE_LIST;Runner.pages.PageSettings.addPageEvent("student_course",pType,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='PPT';if(!pageObj.buttonEventBefore['PPT']){pageObj.buttonEventBefore['PPT']=function(params,ctrl,pageObj,proxy,pageid,rowData){params["txt"]="Exam";ctrl.setMessage("Sending request to server...");}}
if(!pageObj.buttonEventAfter['PPT']){pageObj.buttonEventAfter['PPT']=function(result,ctrl,pageObj,proxy,pageid,rowData){var message=result["txt"]+" !!!";ctrl.setMessage(message);}}
$('a[id=PPT]').each(function(){if(!$(this).closest('tr.gridRowAdd').length){var newId="PPT"+"_"+Runner.genId();this.id=newId;var button_PPT=new Runner.form.Button({id:newId,btnName:"PPT"});button_PPT.init({args:[pageObj,proxy,pageid]});}});});var pType=Runner.pages.constants.PAGE_LIST;Runner.pages.PageSettings.addPageEvent("student_course",pType,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='UP2';if(!pageObj.buttonEventBefore['UP2']){pageObj.buttonEventBefore['UP2']=function(params,ctrl,pageObj,proxy,pageid,rowData){params["txt"]="Exam";ctrl.setMessage("Sending request to server...");}}
if(!pageObj.buttonEventAfter['UP2']){pageObj.buttonEventAfter['UP2']=function(result,ctrl,pageObj,proxy,pageid,rowData){var message=result["txt"]+" !!!";ctrl.setMessage(message);}}
$('a[id=UP2]').each(function(){if(!$(this).closest('tr.gridRowAdd').length){var newId="UP2"+"_"+Runner.genId();this.id=newId;var button_UP2=new Runner.form.Button({id:newId,btnName:"UP2"});button_UP2.init({args:[pageObj,proxy,pageid]});}});});var pType=Runner.pages.constants.PAGE_LIST;Runner.pages.PageSettings.addPageEvent("student_course",pType,"afterPageReady",function(pageObj,proxy,pageid){pageObj.buttonNames[pageObj.buttonNames.length]='PAT';if(!pageObj.buttonEventBefore['PAT']){pageObj.buttonEventBefore['PAT']=function(params,ctrl,pageObj,proxy,pageid,rowData){params["txt"]="Exam";ctrl.setMessage("Sending request to server...");}}
if(!pageObj.buttonEventAfter['PAT']){pageObj.buttonEventAfter['PAT']=function(result,ctrl,pageObj,proxy,pageid,rowData){var message=result["txt"]+" !!!";ctrl.setMessage(message);}}
$('a[id=PAT]').each(function(){if(!$(this).closest('tr.gridRowAdd').length){var newId="PAT"+"_"+Runner.genId();this.id=newId;var button_PAT=new Runner.form.Button({id:newId,btnName:"PAT"});button_PAT.init({args:[pageObj,proxy,pageid]});}});});