<?php
$dalTablestaff_info = array();
$dalTablestaff_info["ID"] = array("type"=>3,"varname"=>"ID");
$dalTablestaff_info["Name"] = array("type"=>200,"varname"=>"Name");
$dalTablestaff_info["StaffNo"] = array("type"=>200,"varname"=>"StaffNo");
$dalTablestaff_info["IC_No"] = array("type"=>200,"varname"=>"IC_No");
$dalTablestaff_info["Email"] = array("type"=>200,"varname"=>"Email");
$dalTablestaff_info["Gender"] = array("type"=>200,"varname"=>"Gender");
$dalTablestaff_info["Race"] = array("type"=>200,"varname"=>"Race");
$dalTablestaff_info["DOB"] = array("type"=>7,"varname"=>"DOB");
$dalTablestaff_info["Address"] = array("type"=>200,"varname"=>"Address");
$dalTablestaff_info["City"] = array("type"=>200,"varname"=>"City");
$dalTablestaff_info["State"] = array("type"=>200,"varname"=>"State");
$dalTablestaff_info["Nationality"] = array("type"=>200,"varname"=>"Nationality");
$dalTablestaff_info["Home_Tel"] = array("type"=>200,"varname"=>"Home_Tel");
$dalTablestaff_info["Mobile_Tel"] = array("type"=>200,"varname"=>"Mobile_Tel");
$dalTablestaff_info["Disability"] = array("type"=>200,"varname"=>"Disability");
$dalTablestaff_info["Medical_condition"] = array("type"=>200,"varname"=>"Medical_condition");
$dalTablestaff_info["Join_Date"] = array("type"=>200,"varname"=>"Join_Date");
$dalTablestaff_info["End_Date"] = array("type"=>200,"varname"=>"End_Date");
$dalTablestaff_info["Gerak_Date"] = array("type"=>200,"varname"=>"Gerak_Date");
$dalTablestaff_info["Job_Type"] = array("type"=>200,"varname"=>"Job_Type");
$dalTablestaff_info["Employee_Type"] = array("type"=>200,"varname"=>"Employee_Type");
$dalTablestaff_info["Job_Title"] = array("type"=>200,"varname"=>"Job_Title");
$dalTablestaff_info["Job_Sesi"] = array("type"=>200,"varname"=>"Job_Sesi");
$dalTablestaff_info["Grade"] = array("type"=>200,"varname"=>"Grade");
$dalTablestaff_info["Elaun"] = array("type"=>200,"varname"=>"Elaun");
$dalTablestaff_info["department"] = array("type"=>200,"varname"=>"department");
$dalTablestaff_info["passport"] = array("type"=>200,"varname"=>"passport");
$dalTablestaff_info["married"] = array("type"=>200,"varname"=>"married");
$dalTablestaff_info["blood"] = array("type"=>200,"varname"=>"blood");
$dalTablestaff_info["photo"] = array("type"=>201,"varname"=>"photo");
$dalTablestaff_info["f1_name"] = array("type"=>200,"varname"=>"f1_name");
$dalTablestaff_info["f1_relation"] = array("type"=>200,"varname"=>"f1_relation");
$dalTablestaff_info["f1_tel"] = array("type"=>200,"varname"=>"f1_tel");
$dalTablestaff_info["f2_name"] = array("type"=>200,"varname"=>"f2_name");
$dalTablestaff_info["f2_relation"] = array("type"=>200,"varname"=>"f2_relation");
$dalTablestaff_info["f2_tel"] = array("type"=>200,"varname"=>"f2_tel");
$dalTablestaff_info["bank1"] = array("type"=>200,"varname"=>"bank1");
$dalTablestaff_info["bank2"] = array("type"=>200,"varname"=>"bank2");
$dalTablestaff_info["epf"] = array("type"=>200,"varname"=>"epf");
$dalTablestaff_info["socso"] = array("type"=>200,"varname"=>"socso");
$dalTablestaff_info["lhdn"] = array("type"=>200,"varname"=>"lhdn");
$dalTablestaff_info["confirmation_date"] = array("type"=>200,"varname"=>"confirmation_date");
$dalTablestaff_info["kelulusan"] = array("type"=>200,"varname"=>"kelulusan");
$dalTablestaff_info["course_opsyen"] = array("type"=>200,"varname"=>"course_opsyen");
$dalTablestaff_info["course_main"] = array("type"=>200,"varname"=>"course_main");
$dalTablestaff_info["sstatus"] = array("type"=>200,"varname"=>"sstatus");
	$dalTablestaff_info["ID"]["key"]=true;
$dal_info["staff_info"]=&$dalTablestaff_info;

?>