<?php
$dalTablestudent_info = array();
$dalTablestudent_info["StudentID"] = array("type"=>3,"varname"=>"StudentID");
$dalTablestudent_info["Name"] = array("type"=>200,"varname"=>"Name");
$dalTablestudent_info["ICNO"] = array("type"=>200,"varname"=>"ICNO");
$dalTablestudent_info["DOB"] = array("type"=>200,"varname"=>"DOB");
$dalTablestudent_info["MatricNo"] = array("type"=>200,"varname"=>"MatricNo");
$dalTablestudent_info["Email"] = array("type"=>200,"varname"=>"Email");
$dalTablestudent_info["Access"] = array("type"=>200,"varname"=>"Access");
$dalTablestudent_info["DateJoin"] = array("type"=>200,"varname"=>"DateJoin");
$dalTablestudent_info["Dateout"] = array("type"=>200,"varname"=>"Dateout");
$dalTablestudent_info["Gender"] = array("type"=>200,"varname"=>"Gender");
$dalTablestudent_info["Address1"] = array("type"=>201,"varname"=>"Address1");
$dalTablestudent_info["City"] = array("type"=>200,"varname"=>"City");
$dalTablestudent_info["Postcode"] = array("type"=>200,"varname"=>"Postcode");
$dalTablestudent_info["StateID"] = array("type"=>200,"varname"=>"StateID");
$dalTablestudent_info["HomeTelephone"] = array("type"=>200,"varname"=>"HomeTelephone");
$dalTablestudent_info["Nationality"] = array("type"=>200,"varname"=>"Nationality");
$dalTablestudent_info["Status"] = array("type"=>200,"varname"=>"Status");
$dalTablestudent_info["Disability"] = array("type"=>200,"varname"=>"Disability");
$dalTablestudent_info["MedicalCondition"] = array("type"=>201,"varname"=>"MedicalCondition");
$dalTablestudent_info["race"] = array("type"=>200,"varname"=>"race");
$dalTablestudent_info["Class"] = array("type"=>200,"varname"=>"fldClass");
$dalTablestudent_info["sesi"] = array("type"=>200,"varname"=>"sesi");
$dalTablestudent_info["tahun"] = array("type"=>16,"varname"=>"tahun");
$dalTablestudent_info["f1_name"] = array("type"=>200,"varname"=>"f1_name");
$dalTablestudent_info["f1_tel"] = array("type"=>200,"varname"=>"f1_tel");
$dalTablestudent_info["f1_relation"] = array("type"=>200,"varname"=>"f1_relation");
$dalTablestudent_info["f1_job"] = array("type"=>200,"varname"=>"f1_job");
$dalTablestudent_info["f2_name"] = array("type"=>200,"varname"=>"f2_name");
$dalTablestudent_info["f2_tel"] = array("type"=>200,"varname"=>"f2_tel");
$dalTablestudent_info["f2_relation"] = array("type"=>200,"varname"=>"f2_relation");
$dalTablestudent_info["f2_job"] = array("type"=>200,"varname"=>"f2_job");
$dalTablestudent_info["blood"] = array("type"=>200,"varname"=>"blood");
$dalTablestudent_info["hostel_in"] = array("type"=>200,"varname"=>"hostel_in");
$dalTablestudent_info["photo"] = array("type"=>201,"varname"=>"photo");
	$dalTablestudent_info["StudentID"]["key"]=true;
$dal_info["student_info"]=&$dalTablestudent_info;

?>